name: Update Ligue 1 Data

on:
  schedule:
    # Cron syntax: "Minutes Heures JourMois Mois JourSemaine"
    # Ici: Ã€ 08h00 UTC, tous les Lundis (1)
    - cron: '2 0 * * 1'
  workflow_dispatch: # Permet de lancer manuellement le script depuis l'interface GitHub si besoin

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pandas pandas-gbq google-auth pyarrow

      - name: Run ETL Script
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          # Si la branche est 'main', on met 'prod', sinon 'dev'
          ENV_TYPE: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
        run: python main.py
